[build]
  command = "next build"
  publish = ".next"

# The Essential Next.js Build Plugin is crucial for Next.js projects.
# Ensure it's installed as a devDependency in your project.
[[plugins]]
  package = "@netlify/plugin-nextjs"
