[build]
  command = "next build"
  publish = ".next"

# The Essential Next.js Build Plugin is usually automatically detected
# by Netlify for Next.js projects. If you encounter issues, you
# might explicitly add it, but try without it first.
# [[plugins]]
#  package = "@netlify/plugin-nextjs"
